/* Populated by react-webpack-redux:action */
export const ADD_COLLAPSER = 'react-scroll-collapse/ADD_COLLAPSER';
export const REMOVE_COLLAPSER = 'react-scroll-collapse/REMOVE_COLLAPSER';
export const EXPAND_COLLAPSE_ALL = 'react-scroll-collapse/EXPAND_COLLAPSE_ALL';
export const HEIGHT_READY_ALL = 'react-scroll-collapse/HEIGHT_READY_ALL';
export const ADD_ITEM = 'react-scroll-collapse/ADD_ITEM';
export const REMOVE_ITEM = 'react-scroll-collapse/REMOVE_ITEM';
export const EXPAND_COLLAPSE = 'react-scroll-collapse/EXPAND_COLLAPSE';
export const TRANSITION_WAIT = 'react-scroll-collapse/TRANSITION_WAIT';
export const HEIGHT_READY = 'react-scroll-collapse/HEIGHT_READY';
export const ADD_SCROLLER = 'react-scroll-collapse/ADD_SCROLLER';
export const REMOVE_SCROLLER = 'react-scroll-collapse/REMOVE_SCROLLER';
export const SET_OFFSET_TOP = 'react-scroll-collapse/SET_OFFSET_TOP';
export const WATCH_INITIALISE = 'react-scroll-collapse/WATCH_INITIALISE';
export const SCROLL_TO = 'react-scroll-collapse/SCROLL_TO';
