import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

import { ofNumberTypeOrNothing } from '../../utils/propTypeHelpers';
import { collapserControllerActions } from '../../actions';
import selectors from '../../selectors';

const { nextCollapserIdSelector } = selectors.collapser;
const { ifNotFirstSec } = selectors.utils;

export const collapserControllerWrapper = (CollapserController) => {

  class WrappedCollapserController extends Component {

    constructor(props, context) {
      super(props, context);
      console.log('WrappedCollapserController: constructor(props, context', props, context);

      const {
        id,
        parentCollapserId,
        parentScrollerId
      } = this.props;
      const collapserId = id;
      /*
        If id vals supplied manually through props use those, else use
        auto-generated values.
      */
      // this.collapserId = ifNotFirstSec(collapserId, nextCollapserIdSelector());
      this.collapserId = collapserId;

      this.parentCollapserId = ifNotFirstSec(parentCollapserId, this.context.parentCollapserId); // eslint-disable-line
      this.parentScrollerId = ifNotFirstSec(parentScrollerId, this.context.parentScrollerId); // eslint-disable-line

      /*
        create state slice for this collapser in redux store.
      */
      this.addCollapser();
    }

    /*
    getChildContext() {
      return {
        parentCollapserId: this.collapserId,
      };
    }
    */

    componentWillUnmount() {
      const { removeCollapserChild, removeScrollerChild, removeCollapser } = this.props;
      if (this.parentCollapserId >= 0) {
        removeCollapserChild(this.parentCollapserId, this.collapserId);
      }
      if (this.parentScrollerId >= 0) {
        removeScrollerChild(this.parentScrollerId, this.collapserId);
      }
      removeCollapser(this.parentCollapserId, this.parentScrollerId, this.collapserId);
    }

    addCollapser() {
      /*
        If you want to allow users to override other collapser attrs, do it
        by adding their props as attrs to the collapser object here.
      */
      const { addCollapser, addScrollerChild, addCollapserChild } = this.props;
      const collapser = { id: this.collapserId };
      addCollapser(this.parentScrollerId, this.parentCollapserId, collapser, this.collapserId);
      if (this.parentScrollerId >= 0) {
        addScrollerChild(this.parentScrollerId, collapser);
      }
      if (this.parentCollapserId >= 0) {
        addCollapserChild(this.parentCollapserId, collapser);
      }
    }

    render() {
      /*
        Pulling these props out so they don't get passed on.  Ignore linting
        error.
      */
      if (this.collapserId >= 0 && this.parentScrollerId >= 0) {
        return (
          <CollapserController
            {...this.props}
            collapserId={this.collapserId}
            parentCollapserId={this.parentCollapserId}
            parentScrollerId={this.parentScrollerId}
          />
        );
      }
      return <div />;
    }
  }

  WrappedCollapserController.defaultProps = {
    collapserId: null,
    parentCollapserId: null,
    parentScrollerId: null,
  };

  WrappedCollapserController.propTypes = {
    addCollapser: PropTypes.func.isRequired,
    addCollapserChild: PropTypes.func.isRequired,
    removeCollapser: PropTypes.func.isRequired,
    removeCollapserChild: PropTypes.func.isRequired,
    addScrollerChild: PropTypes.func.isRequired,
    removeScrollerChild: PropTypes.func.isRequired,

    /*
      Pass the following props if you want to override the autogenerated
      ids.
    */
    collapserId: ofNumberTypeOrNothing,
    parentCollapserId: ofNumberTypeOrNothing,
    parentScrollerId: ofNumberTypeOrNothing,
  };

  /*
    The following relies on the react context api to pass component
    heirarchy information to children.

  WrappedCollapserController.childContextTypes = {
    parentCollapserId: PropTypes.number,
    parentScrollerId: PropTypes.number,
  };

  WrappedCollapserController.contextTypes = {
    parentCollapserId: PropTypes.number,
    parentScrollerId: PropTypes.number,
  };
  */

  return connect(undefined, collapserControllerActions)(WrappedCollapserController);
};

export default collapserControllerWrapper;
